<?php

global $colors_nodes; 

$colors_nodes= array ( 
    "blau-vermell"  => array("nom"=>"Vermell i Blau",        
                                "primary"=>"#ff3257", 
                                "secondary"=>"#4c86a6"),
    "blaus"         => array("nom"=>"Blau clar i Blau fosc", 
                                "primary"=>"#0eb1ff", 
                                "secondary"=>"#087eb6"),
    "groc-blau"     => array("nom"=>"Groc i Blau",
                                "primary"=>"#FFA00C", 
                                "secondary"=>"#3C7C80"),
    "groc-lila"     => array("nom"=>"Groc i lila",           
                                "primary"=>"#ffa00c", 
                                "secondary"=>"#b501c4", 
                                "footer"=>"#ffa00c"),
    "groc-verd"     => array("nom"=>"Groc i verd",           
                                "primary"=>"#fea200", 
                                "secondary"=>"#0f6333"),
    "rosa-gris"     => array("nom"=>"Rosa i Gris",           
                                "primary"=>"#ff3257", 
                                "secondary"=>"#6c6c6c", 
                                "link"=>"#ff3257"),
    "roses"         => array("nom"=>"Roses",
                                "primary"=>"#FF2189", 
                                "secondary"=>"#A41159"),
    "sienna"        => array("nom"=>"Sienna",
                                "primary"=>"#CA5F5F", 
                                "secondary"=>"#763333", 
                                "calendar"=>"#CA5F5F"),
    "taronges"      => array("nom"=>"Taronges",
                                "primary"=>"#FF4C00", 
                                "secondary"=>"#C42300"),
    "taronja-gris"  => array("nom"=>"Taronga i gris",
                                "primary"=>"#FF4C00", 
                                "secondary"=>"#7D7D7D",
                                "link"=>"#FF4C00", 
                                "icon22"=>"#7D7D7D", 
                                "calendar"=>"#FF4C00"),
    "taronja-verd"  => array("nom"=>"Taronga i verd", 
                                "primary"=>"#ff5a26",
                                "secondary"=> "#1fa799"),
    "turqueses"     => array("nom"=>"Turqueses",
                                "primary"=>"#40C3C4",
                                "secondary"=> "#2F5D5D"), 
    "verd-marro"    => array("nom"=>"Verd i Marró",
                                "primary"=>"#00B36B",
                                "secondary"=> "#752800"),
    "verd-rosa"     => array("nom"=>"Rosa i Verd",
                                "primary"=>"#fc3b56",
                                "secondary"=> "#2ca698"), 
    "verds"         => array("nom"=>"Verd clar i Verd fosc",
                                "primary"=>"#55CD00",
                                "secondary"=> "#418000"),
    "vermell-taronja" => array("nom"=>"Vermell i taronja", 
                                "primary"=>"#ff2a2a",
                                "secondary"=> "#ff5a26"),
    "vermell-verd"  => array("nom"=>"Vermell i verd",
                                "primary"=>"#ff2a2a",
                                "secondary"=> "#00854e"), 
    "xocolata"      => array("nom"=>"Xocolata",
                                "primary"=>"#521A09",
                                "secondary"=> "#923917")
);